name: Multiple Env Apps Workflow on Push
on: push
   
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ["gradle:6-jdk8", "gradle:6-jdk11", "gradle:6-jdk17"]
    container: # gradle:6-jdk11
      image: ${{ matrix.container }}    
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4      
      - run: ci/build-app.sh
      - name: test my code
        run: ci/unit-test-app.sh
